[build]
publish = "build"
command = "CI='' npm run build"

[build.environment]
NODE_VERSION = "22.11.0"
NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
